"""AI-based Decision Support dashboard.

Presents an interpretation of the extension portfolio and prioritized,
data-driven recommendations generated by ``app.ml.decision``. Each
recommendation carries a priority and category so institutional decision-makers
can act on the most pressing items first.
"""
from flask import Blueprint, render_template
from flask_login import login_required

from app.ml.decision import build_recommendations

decision_bp = Blueprint("decision", __name__)

_PRIORITY_ICONS = {
    "High": ("bi-arrow-up-right-circle-fill", "text-danger"),
    "Medium": ("bi-exclamation-square-fill", "text-warning"),
    "Low": ("bi-check-circle-fill", "text-success"),
}


@decision_bp.route("/decision-support")
@login_required
def dashboard():
    data = build_recommendations()
    recommendations = data.pop("recommendations")
    return render_template(
        "decision/index.html",
        data=data,
        recommendations=recommendations,
        priority_icons=_PRIORITY_ICONS,
    )