"""In-app notification system.

Notifications are generated by key system events (document classification,
model training, survey data collection, and finance actions) and surfaced to
the logged-in user through a topbar bell. Users can mark individual or all
notifications as read.
"""
from flask import Blueprint, g, jsonify, redirect, render_template, request, url_for
from flask_login import current_user, login_required

from app import db
from app.models import Notification

notifications_bp = Blueprint("notifications", __name__)


def notify(message, category="info", link=None, user=None):
    """Create an in-app notification for the current (or given) user."""
    target = user or current_user
    if target is None:
        return
    db.session.add(Notification(
        user_id=target.id,
        message=message,
        category=category,
        link=link,
    ))
    db.session.commit()


def unread_count(user=None):
    target = user or current_user
    if target is None:
        return 0
    return Notification.query.filter_by(user_id=target.id, is_read=False).count()


@notifications_bp.before_app_request
def _inject_badge():
    """Expose the unread count and recent notifications to every template."""
    try:
        if current_user.is_authenticated:
            g.unread_notifications = unread_count()
            g.recent_notifications = (
                Notification.query
                .filter_by(user_id=current_user.id)
                .order_by(Notification.created_at.desc())
                .limit(8)
                .all()
            )
        else:
            g.unread_notifications = 0
            g.recent_notifications = []
    except Exception:
        g.unread_notifications = 0
        g.recent_notifications = []


@notifications_bp.route("/notifications")
@login_required
def index():
    notifications = (
        Notification.query
        .filter_by(user_id=current_user.id)
        .order_by(Notification.created_at.desc())
        .all()
    )
    return render_template("notifications/index.html", notifications=notifications)


@notifications_bp.route("/notifications/mark-read", methods=["POST"])
@login_required
def mark_read():
    Notification.query.filter_by(user_id=current_user.id, is_read=False).update(
        {"is_read": True}
    )
    db.session.commit()
    return redirect(request.referrer or url_for("notifications.index"))


@notifications_bp.route("/notifications/<int:notification_id>/read", methods=["POST"])
@login_required
def read_one(notification_id):
    n = Notification.query.filter_by(
        id=notification_id, user_id=current_user.id
    ).first_or_404()
    n.is_read = True
    db.session.commit()
    return redirect(n.link or request.referrer or url_for("notifications.index"))


@notifications_bp.route("/notifications/unread-count")
@login_required
def count_json():
    return jsonify({"count": unread_count()})