"""Predictive Analytics dashboard.

Presents trend charts and next-period forecasts generated by
``app.ml.predictive`` so institutional decision-makers can see where
extension activity is heading, plus an interpretation of the numbers.
"""
from flask import Blueprint, render_template
from flask_login import login_required

from app.ml.predictive import build_analytics

predictive_bp = Blueprint("predictive", __name__)


@predictive_bp.route("/predictive")
@login_required
def dashboard():
    data = build_analytics()
    return render_template("predictive/index.html", data=data)